# Generated by Django 3.2 on 2022-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('leverage', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('leverage', models.IntegerField()),
                ('balance_percent', models.FloatField()),
                ('minimal_price', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
